# data-dir contains protobuf files. It's suggested to use fullpath.
data-dir = "./data.drainer"
# If the protobuf files are compressed, specify compression method here.
# Values can be "gzip", or leave it empty if no compression.
compression = "gzip"
# Use index file to search target ts. Set this when `start-ts` is set.
# The file path would be {data-dir}/{index-name}
# index-name = "binlog.index"

# log-file = ""
# log-rotate = "hour"
log-level = "info"

# start-datetime and stop-datetime enable you to pick a range of binlog to restore.
# The datetime format is like '2018-02-28 12:12:12'. 
# start-datetime = ""
# stop-datetime = ""

# Start-tso is similar to start-datetime, but in pd-server tso format. e.g.  395181938313123110
# Stop-tso is is similar to stop-datetime, but in pd-server tso format. e.g. 395181938313123110
# start-tso = 0 
# stop-tso = 0

# work count to execute binlogs
worker-count = 1

# dest-type choose a destination, which value can be "mysql","tidb", "print". 
# for print, it just prints decoded value.
dest-type = "mysql"

##replicate-do-db priority over replicate-do-table if have same db name
##and we support regular expression , start with '~' declare use regular expression.
#
#replicate-do-db = ["~^b.*","s1"]
#[[replicate-do-table]]
#db-name ="test"
#tbl-name = "log"

#[[replicate-do-table]]
#db-name ="test"
#tbl-name = "~^a.*"

[dest-db]
host = "127.0.0.1"
port = 3309
user = "root"
password = ""